apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    appType: web
    appTech: html
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP

