apiVersion: v1
kind: Pod
metadata:
  name: ecomm
  labels:
    tier: frontend
    
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP

